name: Deploy to cspinnacle.github.io

on:
  push:
    branches: [ main ]
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to External GitHub Pages Repository
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out                                  # The folder containing the built site
        repository-name: cspinnacle/cspinnacle.github.io  # The external repository to deploy to
        branch: main                                 # The branch to deploy to
        token: ${{ secrets.EXTERNAL_REPO_TOKEN }}    # PAT with access to the external repo
        clean: true                                  # Remove files from previous deployment
        git-config-name: GitHub Actions Bot          # Set a name for the committer
        git-config-email: noreply@github.com         # Set an email for the committer
        commit-message: "Deploy from cs-site-src: ${{ github.event.head_commit.message || 'Update site' }}"  # Custom commit message
        clean-exclude: |                             # Files to preserve during clean
          .nojekyll
          CNAME